nes (96 sloc) 2.86 KB
 ####################################################
#                                                   #
#         System   Announcement                     #
#                                                   #
####################################################

#Feedreader Sensor
sensor:
  - platform: template
    sensors:
      spk_rss_1:
        value_template: "{{ states.sensor.rss_news_1.attributes.entries[0].title }}" 
        entity_id: sensor.rss_news_1

  - platform: template
    sensors:
      spk_rss_2:
        value_template: "{{ states.sensor.rss_news_2.attributes.entries[0].title }}" 
        entity_id: sensor.rss_news_2

  - platform: template
    sensors:
      spk_rss_3:
        value_template: "{{ states.sensor.rss_news_3.attributes.entries[0].title }}"  
        entity_id: sensor.rss_news_3
  - platform: feedparser
    name: RSS News 1
    feed_url: 'https://vnexpress.net/rss/tin-moi-nhat.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  

  - platform: feedparser
    name: RSS News 2
    feed_url: 'https://thanhnien.vn/rss/home.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  
  - platform: feedparser
    name: RSS News 3
    feed_url: 'https://forbesvietnam.com.vn/rss/home.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  


  - platform: template
    sensors:
      spk_rss_1:
        value_template: "{{ states.sensor.rss_news_1.attributes.entries[0].title }}" 
        entity_id: sensor.rss_news_1

  - platform: template
    sensors:
      spk_rss_2:
        value_template: "{{ states.sensor.rss_news_2.attributes.entries[0].title }}" 
        entity_id: sensor.rss_news_2

  - platform: template
    sensors:
      spk_rss_3:
        value_template: "{{ states.sensor.rss_news_3.attributes.entries[0].title }}"  
        entity_id: sensor.rss_news_3
