 ####################################################
#                                                   #
#         System   Announcement                     #
#                                                   #
####################################################

#Feedreader Sensor
sensor:
  - platform: feedparser
    name: RSS News 1
    feed_url: 'https://vnexpress.net/rss/tin-moi-nhat.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  

  - platform: feedparser
    name: RSS News 2
    feed_url: 'https://thanhnien.vn/rss/home.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  
  - platform: feedparser
    name: RSS News 3
    feed_url: 'https://forbesvietnam.com.vn/rss/home.rss'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - summary    
    exclusions:
      - link
      - description
      - image
      - language
      - pubDate  
      - language  
# Text to speech Custom Component

#TTS of Vietnamese FPT TTS
tts_fpt:
 api_key: 'your_key'
  #See in the /custom_components/tts_fpt/readme.txt for more detail how to create FPT API


#TTS of Vietnamese Viettel TTS
tts_viettel:
 token: 'your Viettel Token' 
   #See in the /custom_components/tts_viettel/readme.txt for more detail how to create Viettel API
 url: 'your hass base URL'
 
#TTS of Google Cloud TTS
tts_ggcloud:
 api: 'your Gooogle API' 
 #See in the /custom_components/tts_ggcloud/readme.txt for more detail how to create Google API
 url: 'your hass base URL'
 
# Service for play some thing
media_extractor:

